<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="Seachange-PC" name="purchase_Admin.Function_DepartmentTest" tests="7" failures="0" timestamp="09 Aug 2017 04:32:04 GMT" time="13.767" errors="1">
  <testcase name="initialioseBrowser" time="13.767" classname="purchase_Admin.Function_DepartmentTest">
    <error type="java.io.FileNotFoundException" message="C:\Users\Priti\workspace\Purchase\Excel\Jibe_Config.xlsx (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\Priti\workspace\Purchase\Excel\Jibe_Config.xlsx (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at common_Function.WriteExcel.writedata(WriteExcel.java:55)
	at common_Function.loginpage.Login(loginpage.java:62)
	at common_Function.WebDriverPass.initialioseBrowser(WebDriverPass.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- initialioseBrowser -->
  <testcase name="FunctionDepartment" time="0.000" classname="purchase_Admin.Function_DepartmentTest">
    <skipped/>
  </testcase> <!-- FunctionDepartment -->
  <testcase name="SearchAddesFunctionDepartment" time="0.000" classname="purchase_Admin.Function_DepartmentTest">
    <skipped/>
  </testcase> <!-- SearchAddesFunctionDepartment -->
  <testcase name="EditFunctionDepartment" time="0.000" classname="purchase_Admin.Function_DepartmentTest">
    <skipped/>
  </testcase> <!-- EditFunctionDepartment -->
  <testcase name="SearchEditedFunctionDepartment" time="0.000" classname="purchase_Admin.Function_DepartmentTest">
    <skipped/>
  </testcase> <!-- SearchEditedFunctionDepartment -->
  <testcase name="DeletetFunctionDepartment" time="0.000" classname="purchase_Admin.Function_DepartmentTest">
    <skipped/>
  </testcase> <!-- DeletetFunctionDepartment -->
  <testcase name="SearchDeletetFunctionDepartment" time="0.000" classname="purchase_Admin.Function_DepartmentTest">
    <skipped/>
  </testcase> <!-- SearchDeletetFunctionDepartment -->
</testsuite> <!-- purchase_Admin.Function_DepartmentTest -->
